name: integration-tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/terraform/**'


jobs:
  build:
    defaults:
      run:
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
        architecture: [ 'x64' ]
    steps:
      # SET UP JDK
      - name: Setup JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}

      - run: java -version

      - run: mvn --version

      - run : mkdir ~/lib

      # BUILD HAZELCAST AZURE SNAPSHOT
      - uses: actions/checkout@v2.3.4
        with:
          path: hazelcast-azure

      - name: Build hazelcast-azure jar
        run: |
          cd hazelcast-azure
          mvn clean install -DskipTests
          echo "Hazelcast Azure jar is: " target/hazelcast-azure-*-SNAPSHOT.jar
          cp target/hazelcast-azure-*-SNAPSHOT.jar ~/lib/hazelcast-azure.jar

      # DOWNLOAD HAZELCAST JAR WITH VERSION DEFINED IN POM.XML
      - name: Download latest Hazelcast version
        run: |
          HZ_VERSION=$(cat hazelcast-azure/pom.xml | grep -m 1 -Po "<hazelcast.version>\K[-_.a-zA-Z0-9]+(?=</hazelcast.version)")
          if [[ $hz_version == *"SNAPSHOT"* ]]; then
            export HZ_JAR_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots"
          else
            export HZ_JAR_REPO_URL="https://repo1.maven.org/maven2"
          fi
          mvn dependency:get -DgroupId=com.hazelcast -DartifactId=hazelcast -Dversion=${HZ_VERSION} \
                  -Dpackaging=jar -DremoteRepositories=${HZ_JAR_REPO_URL}
          cp ~/.m2/repository/com/hazelcast/hazelcast/${HZ_VERSION}/hazelcast-${HZ_VERSION}.jar ~/lib/hazelcast.jar

      #BUILD TERRAFORM
      - name : Set-up Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.13.0

      - name: Create unique prefix for resources
        run: |
          sed -i -e "s/SET_PREFIX/\"${GITHUB_WORKFLOW}-${GITHUB_RUN_ID}\"/g" hazelcast-azure/.github/terraform/terraform.tfvars

      - name: Terraform Init
        run: cd hazelcast-azure/.github/terraform && terraform init

      - name: Terraform Format
        run: cd hazelcast-azure/.github/terraform  && terraform fmt

      - name: Install private key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: " "

      - name: Install public key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: id_rsa.pub
          known_hosts: " "

      - name: Terraform Apply
        run: |
          cd hazelcast-azure/.github/terraform && terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ always() }}
        run: |
          cd hazelcast-azure/.github/terraform && terraform destroy -auto-approve
